### ISSUE TITLE
Editor broken

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#118]
Hi Jared,
after recent changes sulis editor is broken. 
There is 4x this error:
```
error[E0004]: non-exhaustive patterns: `FindLink { .. }` not covered
```
It is probably work in progress, just wanted to test new features. ;-)

**Comment by Grokmoo** [comment]
Should be a quick fix - I will try to find time soon.  I am currently moving my family across the country so have not had much time lately.

**Comment by ernierasta** [comment]
Take your time and good luck with move! I had reverted few commits and it is running ok, so no problem.

**Comment by Grokmoo** [comment]
Finally fixed in master.
