### ISSUE TITLE
Dungeon generator - unpassable region

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#124]
Hi!
Just arrived from vacations and wanted to test Endless Dungeon (great job!). Unfortunately it is possible to generate corridor which is impossible to go through.
Here is screenshot:
![generate-bug](https://user-images.githubusercontent.com/956018/62850573-91217d80-bce3-11e9-8c14-ce562adcb474.png)

And there is second place, on this map, where the same happens.

Would anything else help? Save game, ...

**Comment by Grokmoo** [comment]
Yeah, attaching a savegame should help.

**Comment by ernierasta** [comment]
Hi,
ok, here we go:

http://a.zori.cz/save_20190812-061114.854.json

Let me know, if I can help any further.

**Comment by Grokmoo** [comment]
The most common cases that you are seeing should be fixed now.

Leaving this issue open as it is still possible for props or features to block room entrances.  I think on higher levels this could actually be fine as there are ways around this (teleport, leap).  But, I do want to implement a connectivity check pass which will allow detecting and fixing this type of issue.

**Comment by Grokmoo** [comment]
Should be now resolved.
