### ISSUE TITLE
Progress in 2019

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#146]
Hi Jared,
this is not an issue. I want just to express how I admire your project and how I admire such wonderful open source rpg engine. You made so big progress in last year. Best wishes to you and community around game. Year 2020 will be great and I am excited to see what will happen.

Big fan.

Leszek

I will close the issue few days after New Year.

**Comment by Grokmoo** [comment]
Thanks for the kind words and a very happy new year to you!
