### ISSUE TITLE
In combat mode player character is displaced

### ISSUE THREAD

**Issue by picobyte** [Grokmoo/sulis#154]
When you enter combat mode a non-active party member can become displaced, which seems to be a reproducible bug.
How to trigger
I moved my first character to the top left corner. Above and left of it were trees, which are inaccessible. Then, moved my second character just below the first and one to its right where it became spotted by the enemy. My main character became displaced behind the trees, an inaccessible spot.
The displaced character was still able to aim at certain opponents during battle. After winning combat I went one map back to get the character out.
After loading the just prior save and moving the characters to the exact same spot and handling similarly the same issue occurred.

I just found closed issue #140, so it appears the issue isn't entirely fixed yet, because I built Sulis yesterday from a fresh github clone (master branch). Nice game BTW.

**Comment by Grokmoo** [comment]
Thanks, if I understand you correctly the issue is that a party member gets pushed to a new location that is separate from the main area and can't be pathed out of.  This is a bit different from #140 where the party member got pushed to impassable area - like inside a tree or wall, for example.
