### ISSUE TITLE
Missing a line "to: blazing_road01" after second "responses text" within berkeley04 in razethar.yml

### ISSUE THREAD

**Issue by Mardeg** [Grokmoo/sulis#181]
While testing the game I got to the conversation with Razethar and chose this response at one point:
"I suppose we will have to try.  But, how to return to Rose Lake?"
and the conversation abruptly ended and I couldn't start another one. As a result there was no triggering of the fire_script to run the func: razethar_spoke and without that no new conversation can happen with The Imperator to reveal the door at the Dracon camp to the Blazing Road, so I couldn't continue the game beyond that point.

After exiting the game I manually added a line to the razethar.yml file (after line 138) in  sulis/campaigns/twin_expanse_act2/conversations/razethar.yml so now it looks like:

    - text: "I suppose we will have to try.  But, how to return to Rose Lake?"
      to: blazing_road01

I restarted the game and loaded a savepoint before the conversation with Razethar, chose that same response and this time the conversation and subsequently the game continued properly.

**Comment by Grokmoo** [comment]
Thanks for the bug report and identifying the needed fix.

**Comment by Mardeg** [comment]
What helped make me think this was more of a bug than just "this is as far as the game has been written" was the lack of a diary entry acknowledging the conversation with Razethar had happened. I hadn't thought of the diary as a debugging tool till now!
