### ISSUE TITLE
When attempting to rest in the Ancient Library the disabled message says <PLACEHOLDER>

### ISSUE THREAD

**Issue by Mardeg** [Grokmoo/sulis#182]
Line 13 of the following files in sulis/campaigns/twin_expanse_act2/areas/

ancient_library.yml
ancient_library_level2.yml
ancient_library_level3.yml

all probably need to be changed to something like:

    message: "There are too many enemies about.  You may not rest here."

**Comment by Grokmoo** [comment]
Thanks - already fixed in master in 677c65f6d5d4924c3493f687b76aaf7323bc5d9f
