### ISSUE TITLE
Twin expanse act 1: possible to get infinite xp when talking to Vaalyun's pal

### ISSUE THREAD

**Issue by brian-stovall** [Grokmoo/sulis#193]
When revisiting the rockfall area from the prologue, there is a dialogue tree that grants 50xp for each branch you explore. You can reopen the branches as many times as you want and get the xp reward each time.

**Comment by Grokmoo** [comment]
Thank you very much for the bug report.  Unfortunately the bigger problem is that this quest line goes nowhere at present :)
