### ISSUE TITLE
Stuck in combat mode with no enemies in sight (Mountains of Naath)

### ISSUE THREAD

**Issue by MKRhere** [Grokmoo/sulis#203]
I was playing through the campaign and reached "Act 3: Mountains of Naath", when a mysterious bug keeps me from progressing because the moment I defeat the first group of enemies and move forward, I enter combat mode again, and there are no enemies in sight. Skipping turns indefinitely does nothing. There are a second group of enemies on this map, but defeating them as well does not disable combat mode. Since there's no way to force combat mode to end, the game is hardlocked from progressing. I've attached the save file.

[save_20220327-080658.071.zip](https://github.com/Grokmoo/sulis/files/8357175/save_20220327-080658.071.zip)

**Comment by Grokmoo** [comment]
Thanks for the report - can you also provide your "main.log" file contents.  On Windows, it should be in `Documents\My Games\Sulis\log`.  On Linux, it is in `~/.config/sulis/log` by default.

**Comment by MKRhere** [comment]
`~./config/sulis/log` has one file, "sulis.log". I've attached it here:

[sulis.log](https://github.com/Grokmoo/sulis/files/8377140/sulis.log)

**Comment by Grokmoo** [comment]
Thanks for providing the log file.

It seems like in the attached save, Cragnik is actually occupying the same space as an enemy character.  When I killed that guard and the other visible one, combat did end.

I'm unsure how things ended up in this state - did the guard spawn on top of Cragnik?  Also, how were you able to make a save in this state where the game clearly should be in combat mode?  I'm also interested in how you reached level 63.  Finally, it seems everyone's ability lists are various degrees of broken - no abilities show up at all for most of the party.

Have you used any console commands in this save?    I'm struggling to figure out what happened here to produce this state.

**Comment by MKRhere** [comment]
Hi, thanks for the reply.

### Did the guard spawn on top of Cragnik? How were you able to make a save in this state?

I'm actually not sure how this was possible. I *finished* this combat, **THEN** saved the game (from previous attempts I knew it would hardlock exactly at that point if I proceed), and then proceeded, got hardlocked. There were 4 characters on the top HUD (all my party members and no enemies), and it was in combat mode. While reopening the saved game though, it goes back to the combat which is incomplete.

The guard and Cragnik are in the same spot because I finished the combat, I moved Cragnik, and then saved (just before entering phantom combat mode again). When reopening the save, the dead guard seems to have reappeared on top of Cragnik.

### Levels and broken abilities:

I have the builtin mod "Fast Leveling" enabled, which seems to have broken the character abilities (since level 20 or so? I stopped getting the choose abilities screen, and abilities were broken). I had trouble getting past the first town, since both the bandits and the goblins seemed to be higher level than me, and after about 10 attempts I gave up and enabled the mod. After level 20 or so I wanted to turn it off, but I feared I'd lose levels, so I left it on. Even without the abilities, the characters were able to fight their way through, so I didn't mind.

I have not used any console commands or anything outside what the vanilla game binary provides (including the mod).

**Comment by MKRhere** [comment]
(Apologies, I should've mentioned the Fast Leveling mod was enabled before)

**Comment by MKRhere** [comment]
Amazing, thank you!

**Comment by Grokmoo** [comment]
Ok, I pushed a fix for this issue as well: 2f6483830aef671c25e68f3c3be2ba0ad95b9020.  It is possible you have saves that are in a bad state and will continue to be stuck.  But, in the save you attached, I have tested it and the issue looks to be resolved.

**Comment by MKRhere** [comment]
Works great after building from source :) Thank you, I can explore the rest of the story now!
