### ISSUE TITLE
Liberate proprietary files

### ISSUE THREAD

**Issue by throwaway1037** [Grokmoo/sulis#206]
Please may the proprietary files be released under a [libre](https://freedomdefined.org/Licenses) license?
Some OS distributions such as [Parabola](https://parabola.nu) cannot package games which are not libre.

**Comment by Grokmoo** [comment]
Unfortunately the proprietary files for this project are artwork which I have purchased and do not own the license for.  These are detailed in the [Attribution Sheet](https://github.com/Grokmoo/sulis/blob/master/docs/attribution.csv).

I have spent a lot of time looking for open source licensed art assets.  Unfortunately for some things I just haven't been able to find equivalents that are of good quality.  I do continue to keep an eye out though.

**Comment by throwaway1037** [comment]
That documentation is brilliant.
Would you be against replacing the proprietary files with libre files over time?

So as to prevent the situation from becoming worse as more proprietary files are added, please may I propose instating the policy that all files added from now on must be libre?
