### ISSUE TITLE
Crash in combat after an enemy attack

### ISSUE THREAD

**Issue by RolandDH** [Grokmoo/sulis#207]
[2022-05-22 00:34:12.203872 +02:00] ERROR [sulis_core/src/util.rs:402] Thread main panic with: 'index out of bounds: the len is 16384 but the index is 18446744073709551449'
[2022-05-22 00:34:12.203881 +02:00] WARN [sulis_core/src/util.rs:408] at Some(Location { file: "sulis_state/src/entity_state.rs", line: 378, col: 21 })
[2022-05-22 00:34:12.284433 +02:00] WARN [sulis_core/src/util.rs:411]    0: sulis_core::util::setup_logger::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_bounds_check
   7: sulis_state::entity_state::EntityState::explore_self_location
   8: sulis_state::entity_state::EntityState::attack
   9: rlua::context::StaticUserDataMethods<T>::box_method::{{closure}}
  10: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  11: rlua::util::callback_error
  12: rlua::context::Context::create_callback::call_callback
  13: luaD_call
  14: luaV_execute
  15: luaD_callnoyield
  16: luaD_rawrunprotected
  17: luaD_pcall
  18: lua_pcallk
  19: rlua::function::Function::call
  20: rlua::lua::Lua::context
  21: sulis_state::script::ScriptState::exec_func
  22: sulis_state::script::script_cache::ai_script
  23: sulis_state::script::Script::ai
  24: sulis_state::ai::AI::update
  25: sulis_state::game_state::GameState::update
  26: <main::GameControlFlowUpdater as sulis_core::io::ControlFlowUpdater>::update
  27: sulis_core::io::glium_adapter::main_loop::{{closure}}
  28: winit::platform_impl::platform::x11::EventLoop<T>::run
  29: winit::platform_impl::platform::EventLoop<T>::run
  30: winit::event_loop::EventLoop<T>::run
  31: sulis_core::io::glium_adapter::main_loop
  32: sulis_core::io::System::main_loop
  33: main::main
  34: std::sys_common::backtrace::__rust_begin_short_backtrace
  35: std::rt::lang_start::{{closure}}
  36: std::rt::lang_start_internal
  37: main
  38: __libc_start_call_main
             at /usr/src/debug/sys-libs/glibc-2.35-r5/glibc-2.35/csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  39: __libc_start_main_impl
             at /usr/src/debug/sys-libs/glibc-2.35-r5/glibc-2.35/csu/../csu/libc-start.c:389:3
  40: _start

**Comment by Grokmoo** [comment]
Thank you for the report; I will investigate.
