### ISSUE TITLE
trapped MC

### ISSUE THREAD

**Issue by stop5** [Grokmoo/sulis#208]
campaign: Twin expanse prologue
class: druid

When i fight the goblins before the ravine i can be trapped with my Character.
Prequisites: unlocked spirit eye
I have to use the spirit eye while i am fighting the goblins an send it to the trigger point. Then story is going forward and the helper is teleported behind the ravine without the Character.  if the character has won the fight he is now trapped.

**Comment by Grokmoo** [comment]
Thank you for the report; should now be fixed.
