### ISSUE TITLE
How to add Unicode font in game?

### ISSUE THREAD

**Issue by uiosun** [Grokmoo/sulis#218]
Now I found `sulis/data/fonts` has many english (or europe?) text font, but if I want to add Chinese font, how to do it? -- best way.

i know `characters` part is ASCII code, and Unicode font maybe has more letter, can auto generater it?

Belong issue: https://github.com/Grokmoo/sulis/issues/210

**Comment by Grokmoo** [comment]
Apologies as I mean to reply to this months ago but forgot.  In any given font json file, each character has an associated ID, corresponding to the unicode code point for that character.

**Comment by uiosun** [comment]
Hah, this is Open Source, I used to it.

All right, I will try find or create "Font to JSON" tool, when spare time.
