### ISSUE TITLE
Can't make progress in outskirts 

### ISSUE THREAD

**Issue by grz0** [Grokmoo/sulis#220]
It is impossible to go upwards 
[Screencast_20240506_041920.webm](https://github.com/Grokmoo/sulis/assets/3605541/63bb46b9-18d8-4b71-9f6c-71f8f8a8472a)

**Comment by Grokmoo** [comment]
Thank you for the report.  Fixed in af773b9f09753ea8614ac82dd8033c870a5a779c.

**Comment by do-i** [comment]
This bug is returned. I'm using the `sulis-1.0.0-linux64.zip`.
Everything works great so far until act 3's first hill climb.

![sulis-act3-bug](https://github.com/user-attachments/assets/549b7a0b-9a60-4588-ae01-3bfe34649b58)

**Comment by do-i** [comment]
I built from the latest. And this issue is no longer happening.  Cheers!

**Comment by Grokmoo** [comment]
Thanks for the report.  I definitely need to do a newer release with these fixes.
