### ISSUE TITLE
Question about current status

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#4]
Hi Jared!
I would like to try how the game looks. Is it already good moment to do so? In which phase of development you are now?

Thanx!

**Comment by Grokmoo** [comment]
Hi,

The game is currently in early development.  Most of the systems are in place, but there isn't much to play yet.  I recommend you check back in a few months if you are interested.

Jared

**Comment by ernierasta** [comment]
Thanx for answer!
I do not have really time to play :-D But open source RPG - it is always interesting to keep ready to casually play, when having some time to spend.
Also this may be good opportunity to force myself to become familiar with Rust (go guy here ;-)).

I am closing issue and putting note to my calendar, please add some note to readme, when there will be something to play, even if you only need some tester.

Good luck with your project!
