### ISSUE TITLE
Save while in combat

### ISSUE THREAD

**Issue by Grokmoo** [Grokmoo/sulis#43]
This should be achievable but requires a bit more thought.

Enable saving while in combat mode.
Save turn manager ordering and combat mode status.

**Comment by Grokmoo** [comment]
Not going to do this.

**Comment by Zireael07** [comment]
How long are combats in Sulis? Not being able to save in combat was a major PITA in every game that had that limitation I've played

**Comment by Grokmoo** [comment]
They are at most a few minutes with very few exception.  I can understand your viewpoint, but this feature would have quite a bit of complexity to it.  Realistically, I'm never going to get to it.
