### ISSUE TITLE
Store user game data in .config or .local directory on Linux

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#6]
Hi,
would you consider to store user data(configuration and saves) in XDG compliant directories on Linux? Almost every app do this nowadays. In practice I would use `$XDG_CONFIG_HOME/sulis` to store setting and saves.
So not `$HOME/.sulis` but `$HOME/.config/sulis`.

As said in `https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html` check environment variable and if empty just use `$HOME/.config/sulis`.

It will be easy change now, but harder later, when there will be actual players already.

Btw: checking your progress very often - wow, you are going fast!

**Comment by Grokmoo** [comment]
Ok; I will do that.  Just laziness on my part that I don't already.
