### ISSUE TITLE
automatically end turn

### ISSUE THREAD

**Issue by ernierasta** [Grokmoo/sulis#91]
When player has no AP automatically end turn, so need to press space bar. Would it have any downsides? IMHO no.

**Comment by Grokmoo** [comment]
There is a slight wrinkle here - do we auto end turn if there is less than 1 full AP left - enough for some movement, but nothing else?

**Comment by ernierasta** [comment]
nothing in my opinion, there is still room to move a bit, so let player do that or end turn manually. Maybe root of this problem/potential confusion is in fact, that player do not know if he has any AP left (or did I missed it)?

**Comment by Grokmoo** [comment]
Yeah agreed.  Need to indicate fractional AP in some fashion.

**Comment by ernierasta** [comment]
Maybe if some points left, just show last dot in some color? Maybe very light yellow?
